### ISSUE TITLE
vad returns double the time of the given audio file

### ISSUE THREAD

**Issue by scankurtaran** [bnosac/audio.vadwebrtc#5]
hey there, 

I was using the library to detect silence periods of given audio files, but what I realized is `vad_segments` return double the duration of the given audio,  i.e. for  ~59 sec audio, it returns ~119 sec timestamp.

I would appreciate your help, if I am doing something wrong. here is minimal code, you can reproduce the issue;

```r
remotes::install_github("bnosac/audio.vadwebrtc")
library(audio.vadwebrtc)

audio_file <- file.path(path, "wav_16bit.wav")
vad  <- VAD(audio_file, mode = "normal", milliseconds = 30)

vad_result <- vad$vad_segments
```

**Comment by jwijffels** [comment]
Probably your file is stereo, it should be mono.
You can use R package av to convert it to mono

**Comment by jwijffels** [comment]
Closing as no further feedback is given.
